import type { Metadata } from "next";
import localFont from "next/font/local";
import "../../promisePolyfill";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import "react-pdf/dist/esm/Page/TextLayer.css";
import "react-pdf/dist/esm/Page/AnnotationLayer.css";
import { ToastContainer } from "react-toastify";
import { Navbar, Rightbar, Sidebar } from "@/components/layout";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <ToastContainer />
                <div className="flex sm:flex-row flex-col min-h-screen sm:max-h-screen max-h-fit overflow-hidden">
                    <Navbar />
                    <Sidebar />
                    <div className="overflow-y-auto flex-1">{children}</div>
                    <Rightbar />
                </div>
            </body>
        </html>
    );
}
